### ISSUE TITLE
Не работают страницы

### ISSUE THREAD

**Issue by VladStarr** [qexyorg/webMCR-Ban-List#1]
Поставил последний релиз. Выставил 10 результатов на страницу в конфиге.
В итоге, не вижу блока для перемещения между страницами.

**Comment by qexyorg** [comment]
По умолчанию в конфиге и стоит 10 результатов на страницу.
Если в базе больше 10 записей, то блок для перемещения будет отображаться, иначе - нет.
Действительно ли в базе есть более 10 записей?

**Comment by VladStarr** [comment]
@qexyorg, тестировал и 5, и 10, и 15. В базе намного больше чем 10 банов.
Все равно не отображается.

**Comment by qexyorg** [comment]
Какой используется плагин и что записано в файле configs/bl.cfg.php?

**Comment by VladStarr** [comment]
@qexyorg, Ultrabans.

```
<?php
$cfg = array (
  'install' => false,
  'main' => 'main',
  'title' => 'Банлист',
  'rop_list' => 10,
  'use_us' => false,
  'lvl_access' => -1,
  'lvl_admin' => 15,
  'table' => 'banlist',
  'r_id' => 'id',
  'r_reason' => 'reason',
  'r_by' => 'admin',
  'r_login' => 'name',
  'r_time' => 'time',
  'r_temp' => 'temptime',
  'r_type' => 'type',
);
?>
```

**Comment by qexyorg** [comment]
Отправьте скриншот таблицы banlist в базе.
Не меняли ли код php/html?

**Comment by VladStarr** [comment]
Менял код html.
bl-id.html

```
<tr>
    <td><img src="http://cravatar.eu/helmavatar/<?php
        if ($data['LOGIN'] == 'Starr') {
            echo 'VladStarr';
        } else if ($data['LOGIN'] == 'Lorelei') {
            echo 'BarrowsX';
        } else {
            echo $data['LOGIN']; 
        } 
    ?>/24.png" />&nbsp;&nbsp;<?php echo $data['LOGIN']; ?></td>
    <td><img src="http://cravatar.eu/helmavatar/<?php
        if ($data['BY'] == 'Starr') {
            echo 'VladStarr';
        } else if ($data['BY'] == 'Lorelei') {
            echo 'BarrowsX';
        } else {
            echo $data['BY']; 
        }
    ?>/24.png" />&nbsp;&nbsp;<?php echo $data['BY']; ?></td>
    <td><?php echo $data['TYPE']; ?></td>
    <td><?php
    if ($data['REASON'] == "Unbanned") {
        echo "Неизвестно";
    } else {
        echo $data['REASON'];
    }?></td>
    <td><?php echo $data['BAN_START']; ?></td>
    <td><?php echo $data['BAN_END']; ?></td>
</tr>
```

Скриншот таблицы
![default](https://cloud.githubusercontent.com/assets/13682684/9369586/db8a6f2a-46d2-11e5-8871-bcfd26578375.PNG)

**Comment by VladStarr** [comment]
Может ли быть проблема в том, что сначала при установке webMCR был драйвер PDO, а я поменял в config.php на MySQL, чтобы заработал ваш банлист?

**Comment by qexyorg** [comment]
В ряд ли, но лучше использовать MySQLi.
Так же у вас неверно установлено API http://SSMaker.ru/f496cca7.png (неверные пути к js скриптам)
Попробуйте заменить все стили на стандартные и посмотреть результат.
Так же включите вывод ошибок в файле system.php
- добавьте в начало ini_set('display_errors', true); и замените error_reporting(0); на error_reporting(E_ALL); и посмотрите результат

**Comment by VladStarr** [comment]
Виноват, забыл установить API.
Спасибо!
